@extends('layouts.template')
@section('content')
        <div class="containerr">
            <img src="{{ asset('images/bgplant.jpg') }}" alt="Plant Image">
        </div>
        <div class="index-p">
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Blanditiis dolore laborum, soluta odio veritatis repudiandae porro hic modi cum quidem enim minima voluptates ipsum repellat, iste quas? Molestias beatae eius nam itaque porro et numquam aperiam, aliquam expedita voluptatum natus voluptatem exercitationem ad facilis facere dignissimos nulla minima consequuntur, voluptate deserunt laboriosam! Hic, quo aliquid. A praesentium autem nobis ipsam quo quam consectetur voluptas reiciendis, suscipit totam laborum quia temporibus ex quasi eum beatae eligendi deleniti, nulla rem quos earum itaque fugiat ad! Cum nisi consequatur laboriosam placeat. Illo natus quis ea vitae aspernatur quisquam laboriosam labore itaque facilis illum, consequatur blanditiis dolorum explicabo ipsa officia eos commodi esse cum quaerat laborum animi! Quas harum tenetur quidem repellendus eos earum id, consequatur consectetur dolores itaque eum assumenda ratione molestiae maiores quae aspernatur quis eius vel quam. Aut magnam illum dolorum esse, minima, sint distinctio facilis quas voluptas excepturi fugit? Temporibus pariatur repudiandae quaerat quos reiciendis possimus! Facilis aperiam perspiciatis iste aspernatur. Rem quod fugit suscipit magni ullam ipsum possimus, voluptatibus repellat quas quisquam debitis quasi enim voluptate a, consequatur temporibus dolorum, reprehenderit tenetur eligendi harum! Accusantium eos dolore rerum eaque doloremque, similique beatae, iste molestiae consequatur, reiciendis totam quam dignissimos.</p>
        </div>
        <div class="index-p">
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Blanditiis dolore laborum, soluta odio veritatis repudiandae porro hic modi cum quidem enim minima voluptates ipsum repellat, iste quas? Molestias beatae eius nam itaque porro et numquam aperiam, aliquam expedita voluptatum natus voluptatem exercitationem ad facilis facere dignissimos nulla minima consequuntur, voluptate deserunt laboriosam! Hic, quo aliquid. A praesentium autem nobis ipsam quo quam consectetur voluptas reiciendis, suscipit totam laborum quia temporibus ex quasi eum beatae eligendi deleniti, nulla rem quos earum itaque fugiat ad! Cum nisi consequatur laboriosam placeat. Illo natus quis ea vitae aspernatur quisquam laboriosam labore itaque facilis illum, consequatur blanditiis dolorum explicabo ipsa officia eos commodi esse cum quaerat laborum animi! Quas harum tenetur quidem repellendus eos earum id, consequatur consectetur dolores itaque eum assumenda ratione molestiae maiores quae aspernatur quis eius vel quam. Aut magnam illum dolorum esse, minima, sint distinctio facilis quas voluptas excepturi fugit? Temporibus pariatur repudiandae quaerat quos reiciendis possimus! Facilis aperiam perspiciatis iste aspernatur. Rem quod fugit suscipit magni ullam ipsum possimus, voluptatibus repellat quas quisquam debitis quasi enim voluptate a, consequatur temporibus dolorum, reprehenderit tenetur eligendi harum! Accusantium eos dolore rerum eaque doloremque, similique beatae, iste molestiae consequatur, reiciendis totam quam dignissimos.</p>
        </div>
        <div class="index-p">
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Blanditiis dolore laborum, soluta odio veritatis repudiandae porro hic modi cum quidem enim minima voluptates ipsum repellat, iste quas? Molestias beatae eius nam itaque porro et numquam aperiam, aliquam expedita voluptatum natus voluptatem exercitationem ad facilis facere dignissimos nulla minima consequuntur, voluptate deserunt laboriosam! Hic, quo aliquid. A praesentium autem nobis ipsam quo quam consectetur voluptas reiciendis, suscipit totam laborum quia temporibus ex quasi eum beatae eligendi deleniti, nulla rem quos earum itaque fugiat ad! Cum nisi consequatur laboriosam placeat. Illo natus quis ea vitae aspernatur quisquam laboriosam labore itaque facilis illum, consequatur blanditiis dolorum explicabo ipsa officia eos commodi esse cum quaerat laborum animi! Quas harum tenetur quidem repellendus eos earum id, consequatur consectetur dolores itaque eum assumenda ratione molestiae maiores quae aspernatur quis eius vel quam. Aut magnam illum dolorum esse, minima, sint distinctio facilis quas voluptas excepturi fugit? Temporibus pariatur repudiandae quaerat quos reiciendis possimus! Facilis aperiam perspiciatis iste aspernatur. Rem quod fugit suscipit magni ullam ipsum possimus, voluptatibus repellat quas quisquam debitis quasi enim voluptate a, consequatur temporibus dolorum, reprehenderit tenetur eligendi harum! Accusantium eos dolore rerum eaque doloremque, similique beatae, iste molestiae consequatur, reiciendis totam quam dignissimos.</p>
        </div>
@endsection